# Generated by Django 6.0.2 on 2026-03-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuiviClient', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='confirme_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='token_confirmation',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
